
version: "3"
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.38.0
    restart: always
    networks:
     - nexus 
    volumes:
      - nexus-data:/sonatype/nexus3
    ports:
      - "8081:8081"
volumes:
  nexus-data:
    driver: local
networks:
  nexus:
